### PR TITLE
Use github-rspec

### PR DESCRIPTION
**Pull request by ekohl**
If this works, it should be integrated so it's automatically used. Ideally without making changes to our modules.

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]
I really like the idea and I think we should add that to modulesync_config/voxpupuli-test

**Comment by ekohl** [comment]
This is now integrated in puppetlabs_spec_helper.

**Comment by bastelfreak** [comment]
do we still need to update .rspec/.rspec-parallel?

**Comment by ekohl** [comment]
I think I was confused with Rubocop (https://github.com/puppetlabs/puppetlabs_spec_helper/commit/96dcd841310562344384e0cff908900d9d9f85e5). That means this is still something we should do. Probably in what defines the rake tasks. So that's https://github.com/voxpupuli/beaker-rspec/blob/master/lib/beaker-rspec/rake_task.rb for beaker and https://github.com/puppetlabs/puppetlabs_spec_helper/blob/main/lib/puppetlabs_spec_helper/rake_tasks.rb for unit tests.

**Pull request closed without merging**
